apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maven-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-test
  template:
    metadata:
      labels:
        app: maven-test
    spec:
      containers:
        - name: maven-test
          image: ${REPO}/${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: maven-test
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: maven-test
  selector:
    app: maven-test
  type: LoadBalancer